dependencies:
  flutter: 
  cupertino_icons: 
  provider: 
  drift:
  drift_flutter:
  archive:
  file_picker:
  share_plus:
  path_provider:
  shared_preferences:
  uuid:

dev_dependencies:
  flutter_test:
  drift_dev:
  build_runner:
  flutter_lints:
