name: bd_library_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  drift: ^2.22.1
  drift_flutter: ^2.22.1
  archive: ^3.6.1
  file_picker: ^8.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true